name: Releasing a JAR file
run-name: Releasing a JAR file
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
      - run: echo "🚀 Starting to release a JAR file of the project..."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Release a JAR file
        run: ./release.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
